import linkedin from "../assets/image/linkedin.svg";
import slide from "../assets/image/slide1.jpg";
import Steve1 from "../assets/image/Steve1.jpeg";
import Michaela from "../assets/image/Michaela.jpeg";
import Phuong from "../assets/image/Phuong.jpeg";
import Paulo from "../assets/image/Paulo.jpeg";
import Justin from "../assets/image/Justin.jpeg";
import Cat from "../assets/image/Cat.jpeg";
import Rima from "../assets/image/Rima.jpeg";
export    const testimonials = [
        { name: 'Samuel Daviau', Image: slide, position: 'Co-Founder @UpBeing', text: "Working with Zeeshan has been a privilege. At UpBeing, I've been deeply impressed by her visual, motion, and interaction design skills, her communication with the development team, and her attention to detail. Zeeshan excels at turning concepts into interactive designs with great UX. Beyond her technical expertise, she brings positivity and energy to every project and team, making her a true asset. Her curiosity, drive, and accountability have made working with her an absolute joy.", linkedin },
        { name: 'Steve Reynolds	 ', Image: Steve1, position: '\ Co-Founder @Blue Mountain Software', title: "Steve managed me directly @Rappid Software Design", text: 'I firmly believe that Zeeshan is a naturally gifted designer, particularly in UX/UI, where her passion and dedication truly shine. As someone who values perfection and high standards, I quickly recognized that Zeeshan shares these principles, making her a pleasure to collaborate with. Over time, she refined every detail of her work with impressive creativity and precision. Her passion, skill, and humble determination to learn and succeed are exceptional. I have no doubt she will thrive and excel in any opportunity she pursues.', linkedin },
        { name: 'Michaela Rae', Image: Michaela, position: '\ UX-UI Designer @Red River College Polytechnic ', title: "Michaela worked with me @Brandish Agency", text: 'Zeeshan is an exceptional designer to work with! She has strong design knowledge, problem-solving skills, and is highly reliable and collaborative. Her diverse skill set, including graphic design, motion graphics, and UX, makes her a valuable asset to any team. In my time working with Zeeshan, she was eager to contribute ideas and open to feedback, always willing to revise her work until both the client and agency were satisfied. She’s a quick learner, mastering new tools swiftly, and consistently meets deadlines with dedication and ownership. I highly recommend Zeeshan to any team seeking a talented and hardworking designer.', linkedin },
        { name: 'Phuong Hoang', Image: Phuong, position: '\ Senior Project Manager @Major Tom', title: "Phuong worked with me @Brandish Agency", text: "Zeeshan is who you need when it comes to graphic design. She is known for her hard work and the ability to listen to feedback and provide creative solutions to suit both client and agency's needs.She commits to deadlines and is very proactive in communication to ensure everyone is on the same page.When you work with Zeeshan, you don't need to sugar coat or tip toe around her, your straightforward feedback is what she prefers.", linkedin },
        { name: 'Paulo Ferreira	', Image: Paulo, position: '\ Instructor @Red River College Polytechnic ', title: "Paulo managed me directly @Brandish Agency", text: 'I worked with Zeeshan during our time at Brandish Agency. She brought a lot to the team with her positive attitude that is only comparable with her amazing work ethics. She is a well rounded designer and a joy to have around. If you need to get the job done - count on her', linkedin },
        { name: 'Justin Viloria', Image: Justin, position: '\ Designer @Neo Financial', title: "Justin worked with me @Geofilter", text: 'When I showed Zeeshan the process of how we made designs at our previous job, she was quick and motivated to learn. Within a few days she was able to work on her own without me having to look over her process. Zeeshan is dedicated to get the work completed, and her work ethics is something you don’t see very often. Very friendly. She’s never stressed a day of my life during the time I got to work work with her. I’d be happy to work with her again.', linkedin },
        { name: 'Cat Ross', Image: Cat, position: '\ Founder & President, KIDS Initiative I COO, Winnipeg Humane Society', title: "Cat managed me directly @Winnipeg Humane Society", text: 'Zeeshan has worked tirelessly on multiple design projects for the Winnipeg Humane Society all of which were properly branded, aesthetically pleasing, and vibrant. She comes with innovative ideas and is such a pleasure to work with.', linkedin },
        { name: 'Rima Karapetyan', Image: Rima, position: '\ Strategic Director @The Garden Agency', title: "Rima worked with me @Brandish Agency", text: 'Zeeshan is a talented, dedicated designer and animator with years of experience. Working with her was always easy and it was evident she always put her best work forward. She was always eager to help in ideation sessions, went above and beyond to ensure clients were happy and made an effort to continuously learn and improve in her craft. Working with Zeeshan was a pleasure and I would recommend her to anyone looking for a great, kind, dedicated designer. ', linkedin }
    ];