import linkedin from "../assets/image/linkedin.svg";
import slide from "../assets/image/slide1.jpg";
import Steve1 from "../assets/image/Steve1.jpeg";
import Michaela from "../assets/image/Michaela.jpeg";
import Phuong from "../assets/image/Phuong.jpeg";
import Paulo from "../assets/image/Paulo.jpeg";
import Justin from "../assets/image/Justin.jpeg";
import Cat from "../assets/image/Cat.jpeg";
import Rima from "../assets/image/Rima.jpeg";
export    const testimonials = [
        { name: 'Samuel Daviau', Image: slide, position: 'Co-Founder @UpBeing', text: "Working with Zeeshan has been a privilege. I founded UpBeing and during Zeeshan time working here, I've been incredibly impressed with her visual, motion and interaction design skills, ability to communicate with our development team, attention to detail and ability to transform conceptual visions into interactive product design with strong UX. She's intrinsically curious, driven and accountable. Beyond her technical skills though, Zeeshan brings so much positivity and energy into everything she touches and to everyone she works with. She's been a real culture add and it's been a joy working with her.", linkedin },
        { name: 'Steve Reynolds	 ', Image: Steve1, position: '\ Co-Founder @Blue Mountain Software', title: "Steve managed me directly @Rappid Software Design", text: 'I firmly believe that Zeeshan has a significant level of natural talent in all areas of design, but It was obvious to me that UX/UI design is where she should focus her energy and passion. I consider myself somewhat of a perfectionist and maintain high standards at all times within the realm of UX/UI design and delivery. I recognized early on that Zeeshan shared these same values, and consequently was a pleasure to work with.As she grow into her role, she was able to refine each and every piece of a given design. Zeeshan’s passion, skill and humble yet determined nature to learn and succeed in this space is exceptional, and I have no doubt she will do very well given the opportunity.', linkedin },
        { name: 'Michaela Rae', Image: Michaela, position: '\ UX-UI Designer @Red River College Polytechnic ', title: "Michaela worked with me @Brandish Agency", text: 'Zeeshan is an all around great designer to work with! Not only does she have great design knowledge and problem solving skills, but she is also reliable and a great collaborator. She has a diverse skill set that includes graphic design, motion graphics and UX which makes her an asset to any team! In my time working with Zeeshan she was eager to bring ideas to the table, but also incredibly receptive to feedback; willing to compromise and revise work until both client and agency were happy. She is a quick learner, demonstrating on multiple occasions her ability to learn a new software or tool (seemingly overnight). She consistently meets deadlines and approaches every task with a genuine care and ownership that shows through in her work. I would highly recommend Zeeshan to any agency or company looking for a diverse, thoughtful, and hard-working designer!', linkedin },
        { name: 'Phuong Hoang', Image: Phuong, position: '\ Senior Project Manager @Major Tom', title: "Phuong worked with me @Brandish Agency", text: "Zeeshan is who you need when it comes to graphic design. She is known for her hard work and the ability to listen to feedback and provide creative solutions to suit both client and agency's needs.She commits to deadlines and is very proactive in communication to ensure everyone is on the same page.When you work with Zeeshan, you don't need to sugar coat or tip toe around her, your straightforward feedback is what she prefers.", linkedin },
        { name: 'Paulo Ferreira	', Image: Paulo, position: '\ Instructor @Red River College Polytechnic ', title: "Paulo managed me directly @Brandish Agency", text: 'I worked with Zeeshan during our time at Brandish Agency. She brought a lot to the team with her positive attitude that is only comparable with her amazing work ethics. She is a well rounded designer and a joy to have around. If you need to get the job done - count on her', linkedin },
        { name: 'Justin Viloria', Image: Justin, position: '\ Designer @Neo Financial', title: "Justin worked with me @Geofilter", text: 'When I showed Zeeshan the process of how we made designs at our previous job, she was quick and motivated to learn. Within a few days she was able to work on her own without me having to look over her process. Zeeshan is dedicated to get the work completed, and her work ethics is something you don’t see very often. Very friendly. She’s never stressed a day of my life during the time I got to work work with her. I’d be happy to work with her again.', linkedin },
        { name: 'Cat Ross', Image: Cat, position: '\ Founder & President, KIDS Initiative I COO, Winnipeg Humane Society', title: "Cat managed me directly @Winnipeg Humane Society", text: 'Zeeshan has worked tirelessly on multiple design projects for the Winnipeg Humane Society all of which were properly branded, aesthetically pleasing, and vibrant. She comes with innovative ideas and is such a pleasure to work with.', linkedin },
        { name: 'Rima Karapetyan', Image: Rima, position: '\ Strategic Director @The Garden Agency', title: "Rima worked with me @Brandish Agency", text: 'Zeeshan is a talented, dedicated designer and animator with years of experience. Working with her was always easy and it was evident she always put her best work forward. She was always eager to help in ideation sessions, went above and beyond to ensure clients were happy and made an effort to continuously learn and improve in her craft. Working with Zeeshan was a pleasure and I would recommend her to anyone looking for a great, kind, dedicated designer. ', linkedin }
    ];